[tool.poetry]
name = "elevate-be"
version = "0.1.0"
description = "Elevate"
authors = ["ArJSarmiento <rneljan@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
aws-cdk-lib = "2.147.3"
constructs = ">=10.0.0,<11.0.0"
aws-lambda-powertools = "^2.40.1"


[tool.poetry.group.dev.dependencies]
pytest = "6.2.5"
ruff = "0.5.1"
boto3-stubs = "^1.34.140"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.format]
quote-style = "single"
docstring-code-line-length = "dynamic"
indent-style = "space"
docstring-code-format = false
line-ending = "auto"


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []