name: Deploy Elevate Backend
on:
    workflow_run:
      workflows: ["Formatting Check on Push Workflow"]
      types:
        - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'stage') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - uses: actions/setup-python@v5
        with:
         python-version: '3.10' 

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --without dev,format

      - name: Deploy with Serverless
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          poetry run cdk deploy --all --require-approval --context prod never
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
          poetry run cdk deploy --all --require-approval --context stage never
          fi